# Site Settings
baseurl: ""
url: "navskh.github.io"

# Blog Setting
blog: True
dolist_days: 7
dolist_version: 2

# Language of the website
lang: en

# Search engine optimization settings
title: Young's Blog
tagline: Young's Devlog
description: The demonstration page for the Young's skill, project, blog
author: Young(navskh)
twitter:
  username: navskh
  card: A jekyll theme for academic portfolios
logo: /assets/img/profile2.jpg
social:
  name: Young Sung
  links:
    - https://twitter.com/NavskhYoung
    - https://github.com/navskh
locale: en_GB

# Page Settings
theme_settings:
  title: Young's Devlog

  experience_title: EXPERIENCE
  interests_title: STUDY INTERESTS
  skills_title: SKILLS
  projects_title: PROJECTS
  recentpubs_title: RECENT PUBLICATIONS

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Collection
collections:
  dolist: 
    output: true

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

# Bibliography settings
scholar:
  bibliography: publications.bib
  bibliography_template: pubstemplate
  style: apa
  locale: en
  last_name: Me
  first_name: [Myself, M.]
  sort_by: year,month
  order: descending,ascending

# markdown setting
markdown: kramdown
kramdown: 
  input: GFM
  highlighter: rouge 

filtered_bibtex_keywords: [abbr, abstract, arxiv, bibtex_show, html, pdf, selected, supp, blog, code, poster, slides, website] # Filter out certain bibtex entry keywords used internally from the bib output

# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-1F0YEZJTGZ"
    anonymize_ip         : # true, false (default)

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
